### Topics:
- own module creation and usage
- python advanced packages intro
    - numpy
    - pandas
    - matplotlib

In [1]:
import functions
functions.pi

3.14

In [2]:
functions.name

'math'

In [1]:
import functions as f
f.name

'math'

In [4]:
dir(f)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'name',
 'pi',
 'sqrt',
 'welcome']

In [2]:
help(f.sqrt)

Help on function sqrt in module functions:

sqrt(n)
    it will print the square root of number n



In [3]:
def welcome(name):
    ''' it will print the name with welcome'''
    print("Welcome "+name)
help(welcome)

Help on function welcome in module __main__:

welcome(name)
    it will print the name with welcome



In [4]:
f.sqrt(9)

3.0


In [13]:
import numpy as np
a = np.array([34,56,99],dtype=np.int16)
print(type(a))

<class 'numpy.ndarray'>


In [14]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.itemsize)
print(a.dtype)

1
(3,)
3
2
int16


In [10]:
a2 = np.array([[34,56,99],[5,8,9]])
print(a2.size,a2.itemsize)

6 4


In [15]:
L = [45,78,89,77,90]
#O/p 50,83,94,82,95
L + 5

TypeError: can only concatenate list (not "int") to list

In [16]:
for i in range(len(L)):
    L[i] = L[i] +5
print(L)

[50, 83, 94, 82, 95]


In [17]:
print(L)
L = list(map(lambda x: x+5,L))
print(L)

[50, 83, 94, 82, 95]
[55, 88, 99, 87, 100]


In [18]:
L = np.array(L)
print(type(L))
L + 5

<class 'numpy.ndarray'>


array([ 60,  93, 104,  92, 105])

In [20]:
L2 = np.array([1,2,3,4,5])
print(L)
print(L2)
print(L+L2)
print(L*L2)

[ 55  88  99  87 100]
[1 2 3 4 5]
[ 56  90 102  91 105]
[ 55 176 297 348 500]


In [ ]:
values = list(range(1000000))
lvalues = [i**2 for i in values]
avalues = np.array(values)
asvalues = avalues ** 2


In [2]:
import numpy as np
np.arange(10,55,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [3]:
np.linspace(10,55,5)

array([10.  , 21.25, 32.5 , 43.75, 55.  ])

In [4]:
np.linspace(10,55,4)

array([10., 25., 40., 55.])

**Other functions to create numpy arrays**
- np.ones
- np.zeros
- np.full
- np.eye
- np.diag<br>

**packages**
- np.random
- np.linalg

In [6]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [8]:
np.arange(100).reshape(10,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [14]:
import pandas as pd
df = pd.read_csv("marks.csv")

In [15]:
df

name  marks  rollno
0  giri     67       1
1  hari     89       2
2  raju     99       3
3  rani     84       4

In [11]:
type(df)

pandas.core.frame.DataFrame

In [16]:
df.shape

(4, 3)

In [17]:
df['name']

0    giri
1    hari
2    raju
3    rani
Name: name, dtype: object

In [18]:
df['marks'].mean()

84.75

In [19]:
pd.__version__

'0.24.2'

In [20]:
np.__version__

'1.16.4'